### ISSUE TITLE
Dockerhub autobuild update

### ISSUE THREAD

**Issue by clburlison** [grahamgilbert/sal-saml#8]
# Issue
When a new release of this docker container is created dockerhub currently attempts to rebuilds all branches instead of just the most recent version + latest. This means build times for new releases are crazy long until/unless Graham goes into the dockerhub GUI and cancels old builds.

# Potential fix
I've tested the following on my fork sal-saml and the following autobuild settings fixed this for me.

| Type   | Name                              | Dockerfile Location | Docker Tag Name |
|--------|-----------------------------------|---------------------|-----------------|
| Branch | master                            | /                   | latest          |
| Branch    | /^([0-9]+)\.([0-9]+)\.([0-9]+)$/ | /                   | {\1}.{\2}.{\3}  |
| Branch    | /^([0-9]+)\.([0-9]+)\.([0-9]+)\.([0-9]+)$/ | /                   | {\1}.{\2}.{\3}.{\4}  |

This should limit dockerhub to only build branches in the format of `X.X.X` or patches named `X.X.X.X`. Then when a new branch is pushed dockerhub only builds the new branch.

based off: https://stackoverflow.com/a/44796846

**Comment by grahamgilbert** [comment]
But it also has no way of rebuilding boxes to catch a change made upstream, unless I've missed that,

**Comment by clburlison** [comment]
Closing stale issues. Your previous comment is correct, not as easy as I thought. 😢
